---
title: "Homework 5"
author: "Vasili Fokaidis"
output: github_document
---

```{r}
library(tidyverse)
library(dplyr)
```

## Problem 1

Read in the data.

```{r}
homocide_df = 
  read_csv("data/homicide-data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  ) %>%
  select(city_state, resolved) %>%
  filter(city_state != "Tulsa_AL")
```

Let's look at this a bit

```{r}
aggregate_df =
homocide_df %>%
  group_by(city_state) %>%
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)) %>%
  broom::tidy()
```

Try to iterate ........

```{r}
results_df =
aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)),
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
  ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```

```{r}
results_df %>%
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r}
city_prop_test = function(df) {
  
  n_unsolved ...
  n_total ...
  
  prop.test(.....)
  
}
```


## Problem 2 ideas ...

import one dataset

```{r}
data_1 = read_csv("ldl_data/con_01.csv")
```

```{r}
path_df =
tibble(
  path = list.files("ldl_data")
  ) %>%
mutate(
  path = str_c("ldl_data/", path),
   data = map(............))

read_csv(path_df$path[[1]])
```

